// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package drivercampaign

import (
	"github.com/BiTaksi/drivercampaign/internal/handler"
	"github.com/BiTaksi/drivercampaign/internal/route"
	"github.com/BiTaksi/drivercampaign/pkg/requestclient"
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func InitHealthCheckHandler() handler.IHealthCheckHandler {
	iHealthCheckHandler := handler.NewHealthCheckHandler()
	return iHealthCheckHandler
}

func InitRoute(l *logrus.Logger, rqInstance requestclient.IRequestClient) route.IRoute {
	iHomeHandler := handler.NewHomeHandler()
	iRoute := route.NewRoute(iHomeHandler)
	return iRoute
}

// wire.go:

var handlerProviders = wire.NewSet(handler.NewHomeHandler)

var allProviders = wire.NewSet(
	handlerProviders,
)
