// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/requestclient/requestclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	requestclient "github.com/BiTaksi/drivercampaign/pkg/requestclient"
	gomock "github.com/golang/mock/gomock"
)

// MockIRequestClient is a mock of IRequestClient interface.
type MockIRequestClient struct {
	ctrl     *gomock.Controller
	recorder *MockIRequestClientMockRecorder
}

// MockIRequestClientMockRecorder is the mock recorder for MockIRequestClient.
type MockIRequestClientMockRecorder struct {
	mock *MockIRequestClient
}

// NewMockIRequestClient creates a new mock instance.
func NewMockIRequestClient(ctrl *gomock.Controller) *MockIRequestClient {
	mock := &MockIRequestClient{ctrl: ctrl}
	mock.recorder = &MockIRequestClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRequestClient) EXPECT() *MockIRequestClientMockRecorder {
	return m.recorder
}

// GetReq mocks base method.
func (m *MockIRequestClient) GetReq(ctx context.Context, headers map[string]string, url string) (*requestclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReq", ctx, headers, url)
	ret0, _ := ret[0].(*requestclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReq indicates an expected call of GetReq.
func (mr *MockIRequestClientMockRecorder) GetReq(ctx, headers, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReq", reflect.TypeOf((*MockIRequestClient)(nil).GetReq), ctx, headers, url)
}

// HandleRequest mocks base method.
func (m *MockIRequestClient) HandleRequest(ctx context.Context, req requestclient.Request) (*requestclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRequest", ctx, req)
	ret0, _ := ret[0].(*requestclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleRequest indicates an expected call of HandleRequest.
func (mr *MockIRequestClientMockRecorder) HandleRequest(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRequest", reflect.TypeOf((*MockIRequestClient)(nil).HandleRequest), ctx, req)
}
